pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/SreekardesikJetti/hellojenkins'
            }
        }

        stage('Debug') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

     stage('Build') {
    steps {
        dir('hellojenkins') {
            sh 'mvn clean install'
        }
    }



       stage('Run') {
    steps {
        dir('hellojenkins') {
            sh 'nohup java -jar target/*.jar &'
        }
    }
}

}



